"""empty message

Revision ID: 00827630aa92
Revises: 28d9b6ab2140
Create Date: 2020-02-06 15:24:45.229492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00827630aa92'
down_revision = '28d9b6ab2140'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_groups_authorities', sa.Column('status', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog_groups_authorities', 'status')
    # ### end Alembic commands ###
