"""empty message

Revision ID: 514a967d2f2b
Revises: 33cde7a9ffc5
Create Date: 2020-02-05 19:16:39.638931

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '514a967d2f2b'
down_revision = '33cde7a9ffc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_post_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('blog_post_reply', sa.Column('cid', sa.Integer(), nullable=False))
    op.drop_column('blog_post_reply', 'post_id')
    op.drop_column('blog_post_reply', 'pid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_post_reply', sa.Column('pid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('blog_post_reply', sa.Column('post_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('blog_post_reply', 'cid')
    op.drop_table('blog_post_comment')
    # ### end Alembic commands ###
