"""empty message

Revision ID: 750bd119eee6
Revises: a50711bff106
Create Date: 2020-02-05 12:07:42.317949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '750bd119eee6'
down_revision = 'a50711bff106'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_users', sa.Column('avatar', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog_users', 'avatar')
    # ### end Alembic commands ###
