"""empty message

Revision ID: d52b424eefea
Revises: dff8c9a5fc47
Create Date: 2020-02-05 12:06:02.897136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd52b424eefea'
down_revision = 'dff8c9a5fc47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_users', sa.Column('avatar', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog_users', 'avatar')
    # ### end Alembic commands ###
