"""empty message

Revision ID: dff8c9a5fc47
Revises: 404f0f4fd46a
Create Date: 2020-02-05 10:29:39.827411

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dff8c9a5fc47'
down_revision = '404f0f4fd46a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog_users_avatar', 'md5')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_users_avatar', sa.Column('md5', mysql.VARCHAR(length=128), nullable=True))
    # ### end Alembic commands ###
